- type: application/vnd.org.wtwta.project
  main: lcars-sdk-mpe
  id: lcars-sdk-mpe
  name: LCARS-SDK (fork)
  slug-id: LCARS-SDK
  repositories:
    origin: http://github.com/dotmpe/LCARS-SDK.git
    gh: git@github.com:dotmpe/LCARS-SDK.git
    aric: git@github.com:Aricwithana/LCARS-SDK.git
